package com.group2.catanbackend.dto.game;

public interface GameMoveType {
    String BUILDROADMOVE = "BUILD_ROAD_MOVE";
    String BUILDVILLAGEMOVE = "BUILD_VILLAGE_MOVE";
    String BUILDCITYMOVE = "BUILD_CITY_MOVE";
    String ENTTURNMOVE = "END_TURN_MOVE";
    String ROLLDICEMOVE = "ROLL_DICE_MOVE";
    String MOVEROBBERMOVE = "MOVE_ROBBER_MOVE";
    String ACCUSECHEATINGMOVE="ACCUSE_CHEATING_MOVE";
}
